[project]
name = "ru-movie-rag"
version = "0.1.0"
description = "RU titles + overviews for RAG via TMDB + kinopoisk.dev + ru.wikipedia"
authors = ["you"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
pull = "python src/rag_movies_ru.py pull"
batch = "python src/rag_movies_ru.py batch"
top = "python src/rag_movies_ru.py top"

[dependencies]
pixi-pycharm = "*"
python = "3.10.*"

[pypi-dependencies]
requests = ">=2.32.5, <3"
python-dotenv = ">=1.1.1, <2"
pandas = ">=2.3.3, <3"
